services:
  mkdocs:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mydocs
    ports:
      - "8000:80"
    networks:
      - mkdocs_networks
    volumes:
      - ./site:/usr/share/nginx/html

networks:
  mkdocs_networks:
    driver: bridge